// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteClientDeauthorizeData, DeleteClientDeauthorizeErrors, DeleteClientDeauthorizeResponses, GetClientAuthorizeData, GetClientAuthorizeErrors, GetClientAuthorizeResponses, GetClientUpdateCheckData, GetClientUpdateCheckResponses, GetStateFetchData, GetStateFetchErrors, GetStateFetchResponses, PostStateSyncData, PostStateSyncErrors, PostStateSyncResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Get a client's state by uuid
 */
export const getStateFetch = <ThrowOnError extends boolean = false>(options: Options<GetStateFetchData, ThrowOnError>): RequestResult<GetStateFetchResponses, GetStateFetchErrors, ThrowOnError> => (options.client ?? client).get<GetStateFetchResponses, GetStateFetchErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/get/{uuid}',
    ...options
});

/**
 * Authorize a secondary client
 */
export const getClientAuthorize = <ThrowOnError extends boolean = false>(options: Options<GetClientAuthorizeData, ThrowOnError>): RequestResult<GetClientAuthorizeResponses, GetClientAuthorizeErrors, ThrowOnError> => (options.client ?? client).get<GetClientAuthorizeResponses, GetClientAuthorizeErrors, ThrowOnError>({ url: '/api/auth/{uuid}', ...options });

/**
 * Deauthorize all clients and delete stored data
 */
export const deleteClientDeauthorize = <ThrowOnError extends boolean = false>(options: Options<DeleteClientDeauthorizeData, ThrowOnError>): RequestResult<DeleteClientDeauthorizeResponses, DeleteClientDeauthorizeErrors, ThrowOnError> => (options.client ?? client).delete<DeleteClientDeauthorizeResponses, DeleteClientDeauthorizeErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/deauth/{uuid}',
    ...options
});

/**
 * Create or update the client's state
 */
export const postStateSync = <ThrowOnError extends boolean = false>(options: Options<PostStateSyncData, ThrowOnError>): RequestResult<PostStateSyncResponses, PostStateSyncErrors, ThrowOnError> => (options.client ?? client).post<PostStateSyncResponses, PostStateSyncErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/sync/{uuid}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Provide information about the latest release
 */
export const getClientUpdateCheck = <ThrowOnError extends boolean = false>(options?: Options<GetClientUpdateCheckData, ThrowOnError>): RequestResult<GetClientUpdateCheckResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetClientUpdateCheckResponses, unknown, ThrowOnError>({ url: '/api/update', ...options });
