// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8111' | (string & {});
};

export type GetStateFetchData = {
    body?: never;
    path: {
        /**
         * Target client UUID
         */
        uuid: string;
    };
    query?: never;
    url: '/api/get/{uuid}';
};

export type GetStateFetchErrors = {
    /**
     * Unauthorized
     */
    401: {
        error: string;
    };
    /**
     * State not found
     */
    404: {
        error: string;
    };
};

export type GetStateFetchError = GetStateFetchErrors[keyof GetStateFetchErrors];

export type GetStateFetchResponses = {
    /**
     * Returns state for uuid if found
     */
    200: {
        hashedPassword?: string;
        dailyTimeLimit: number;
        todayTimeLimit: number;
        usedTime?: number;
        usageDate: string;
        bedtime: string;
        waketime: string;
        syncAuthor?: string | null;
        clientVersion?: string;
        clientOS?: string;
    };
};

export type GetStateFetchResponse = GetStateFetchResponses[keyof GetStateFetchResponses];

export type GetClientAuthorizeData = {
    body?: never;
    path: {
        /**
         * Target client UUID
         */
        uuid: string;
    };
    query: {
        /**
         * Client's password
         */
        password: string;
    };
    url: '/api/auth/{uuid}';
};

export type GetClientAuthorizeErrors = {
    /**
     * Unauthorized
     */
    401: {
        success: boolean;
        error: string;
    };
    /**
     * Client not found
     */
    404: {
        success: boolean;
        error: string;
    };
};

export type GetClientAuthorizeError = GetClientAuthorizeErrors[keyof GetClientAuthorizeErrors];

export type GetClientAuthorizeResponses = {
    /**
     * Generates a new auth key for this client
     */
    200: {
        success: boolean;
        authKey: string;
    };
};

export type GetClientAuthorizeResponse = GetClientAuthorizeResponses[keyof GetClientAuthorizeResponses];

export type DeleteClientDeauthorizeData = {
    body?: never;
    path: {
        /**
         * Target client UUID
         */
        uuid: string;
    };
    query?: never;
    url: '/api/deauth/{uuid}';
};

export type DeleteClientDeauthorizeErrors = {
    /**
     * Unauthorized
     */
    401: {
        success: boolean;
        error: string;
    };
    /**
     * Client not found
     */
    404: {
        success: boolean;
        error: string;
    };
};

export type DeleteClientDeauthorizeError = DeleteClientDeauthorizeErrors[keyof DeleteClientDeauthorizeErrors];

export type DeleteClientDeauthorizeResponses = {
    /**
     * Generates a new auth key for this client
     */
    200: {
        success: boolean;
    };
};

export type DeleteClientDeauthorizeResponse = DeleteClientDeauthorizeResponses[keyof DeleteClientDeauthorizeResponses];

export type PostStateSyncData = {
    body?: {
        hashedPassword?: string;
        dailyTimeLimit?: number;
        todayTimeLimit?: number;
        usedTime?: number;
        usageDate?: string;
        bedtime?: string;
        waketime?: string;
        syncAuthor?: string | null;
        clientVersion?: string;
        clientOS?: string;
    };
    path: {
        /**
         * Target client UUID
         */
        uuid: string;
    };
    query?: {
        /**
         * Overrides values even if they are different from what you expected.
         */
        parentMode?: boolean | null;
    };
    url: '/api/sync/{uuid}';
};

export type PostStateSyncErrors = {
    /**
     * Unauthorized
     */
    401: {
        accepted: boolean;
        error: string;
    };
};

export type PostStateSyncError = PostStateSyncErrors[keyof PostStateSyncErrors];

export type PostStateSyncResponses = {
    /**
     * Returns accepted if your changes were accepted, and any fields that might be different from your submission
     */
    200: {
        accepted: boolean;
        delta?: {
            hashedPassword?: string;
            dailyTimeLimit?: number;
            todayTimeLimit?: number;
            usedTime?: number;
            usageDate?: string;
            bedtime?: string;
            waketime?: string;
            syncAuthor?: string | null;
            clientVersion?: string;
            clientOS?: string;
        };
    };
};

export type PostStateSyncResponse = PostStateSyncResponses[keyof PostStateSyncResponses];

export type GetClientUpdateCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/update';
};

export type GetClientUpdateCheckResponses = {
    /**
     * Returns the latest version number
     */
    200: {
        version: string;
    };
};

export type GetClientUpdateCheckResponse = GetClientUpdateCheckResponses[keyof GetClientUpdateCheckResponses];
